### ISSUE TITLE
Unable to cancel subscription

### ISSUE THREAD

**Issue by russellsmith** [HowToHockey/ThePond#30]
I was attempting to cancel my subscription to try to reactivate with HTHEarlyBird2020 code (though I'm not sure if it'd work =).  When clicking cancel I got this error:

<img width="1237" alt="Screen Shot 2020-12-19 at 8 15 32 AM" src="https://user-images.githubusercontent.com/654652/102693987-10c23500-41d3-11eb-959a-282963d1b056.png">

Interestingly, I didn't pay with paypal. I used the stripe test credit card number, so there's no recurring payment info on my PayPal account.

**Comment by HadenHiles** [comment]
Hmm, interesting... it says in our system that it was cancelled successfully, and it appears that in your image it did as well. But I have no idea why a paypal error would show up lol. I think possibly since you used the test card, but it's no longer in test mode that when it tried to cancel it gave an error and the paypal one is just the last one that caught the exception... I'll remove the old subscription so at least you don't have to look at it in your account ;) lol

Thanks for reporting this.

**Comment by HadenHiles** [comment]
Oh and also, I updated it so you get the $6.99 rate. Neglected to mention that important part lol. Cheers!

**Comment by russellsmith** [comment]
The system definitely still thinks my account is linked to PayPal.  When I click on Update for my current Subscription to try to add real billing info I see this page telling me to go to my PayPal account:

<img width="1440" alt="Screen Shot 2020-12-20 at 8 18 58 AM" src="https://user-images.githubusercontent.com/654652/102718336-78908280-429c-11eb-8211-8a334fe0b429.png">

I think when I first attempted to sign up I tried PayPal first which failed, then I tried the Stripe test CC.  Maybe the first attempt actually linked PayPal to my account?  

It looks like the subscription will attempt billing tomorrow so we'll see what happens lol
